### ISSUE TITLE
migrate to vitejs from create-react-app

### ISSUE THREAD

**Issue by anmarchenko** [anmarchenko/igroteka_fe#30]
## Resources

- [migrate from cra to vite](https://www.robinwieruch.de/vite-create-react-app/)
- [also migrate](https://sankalan.hashnode.dev/migrate-your-create-react-app-to-vite-easily)
- [another guide](https://cathalmacdonnacha.com/migrating-from-create-react-app-cra-to-vite)

**Comment by RISHIKESHk07** [comment]
hey there @anmarchenko , i  would like to contribute
